In [ ]:
'''
Unique and Count Values in NumPy

NumPy provides functions to find:

Unique values
Count of unique values
Frequency of each value
'''

In [1]:
import numpy as np

In [ ]:
# 1. np.unique()

a = np.array([1,2,2,3,4,4,5])

result = np.unique(a)

print(result)

[1 2 3 4 5]


In [3]:
# 2. Unique Values with Counts

a = np.array([1,2,2,3,4,4,4,5])

values, counts = np.unique(a, return_counts=True)

print("Unique Values:", values)
print("Counts:", counts)

Unique Values: [1 2 3 4 5]
Counts: [1 2 1 3 1]


In [4]:
# 3. Loop Through Values and Counts

a = np.array([10,20,20,30,30,30])

values, counts = np.unique(a, return_counts=True)

for v, c in zip(values, counts):
    print(v, "appears", c, "times")

10 appears 1 times
20 appears 2 times
30 appears 3 times


In [5]:
# 4. Count Specific Value

a = np.array([1,2,2,2,3,4])

count = np.sum(a == 2)

print(count)

3


In [6]:
# 5. Count Non-Zero Values

a = np.array([0,1,2,0,3,0,4])

count = np.count_nonzero(a)

print(count)

4


In [7]:
# 6. Unique Values in 2D Array

a = np.array([[1,2],
              [2,3]])

result = np.unique(a)

print(result)

[1 2 3]


In [ ]:
'''
Important Functions

| Function             | Meaning               |
| -------------------- | --------------------- |
| `np.unique()`        | Find unique values    |
| `return_counts=True` | Count frequency       |
| `np.sum(a==x)`       | Count specific value  |
| `np.count_nonzero()` | Count non-zero values |

'''

In [8]:
import numpy as np

a = np.array([5,10,10,15,15,15,20])

values, counts = np.unique(a, return_counts=True)

print(values)
print(counts)

[ 5 10 15 20]
[1 2 3 1]
