In [ ]:
# Boolean indexing

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [3]:
arr > 25

array([False, False,  True,  True,  True])

In [4]:
# Multiple Conditions
# AND condition

arr[(arr > 5) & (arr < 20)]

array([10])

In [5]:
# OR condition

arr[(arr < 10) | (arr > 20)]

array([30, 40, 50])

In [ ]:
# Boolean Mask
# The condition array: is called a Boolean Mask.

arr > 10

array([False,  True,  True,  True,  True])

In [7]:
# 2D Array Example

arr = np.array([[10, 20],
                [30, 40]])

print(arr[arr > 20])

[30 40]
