In [ ]:
# Slicing in Numpy Array

In [1]:
import numpy as np

In [ ]:
# 1d array
array1 = np.array([10, 20, 30, 40, 50, 60, 70])
print(array1)

[10 20 30 40 50 60 70]


In [ ]:
# start indexing and stop indexing
print(array1[1:3])

[20 30]


In [ ]:
# start indexing and stop indexing and step (gap) is two here
print(array1[1:6:2])

[20 40 60]


In [5]:
print(array1[-1:-3:-1])

[70 60]


In [ ]:
# :: start and end value not mentioned and 2 means gap/step
print(array1[::2])

[10 30 50 70]


In [ ]:
# reverse
print(array1[::-1])

[70 60 50 40 30 20 10]


In [ ]:
# 2d array (4x3 matrix = 12 toatal)
#                   0   1   2 --> column
array2 = np.array([[10, 20, 30], # 0 rows
                  [40, 50, 60], # 1 rows
                  [70, 80, 90], # 2 rows
                  [100, 110, 120]]) # 3 rows
print(array2)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [ ]:
# rows first after comma column come
print(array2[1,])

[40 50 60]


In [18]:
print(array2[:,1])

[ 20  50  80 110]


In [19]:
# row and column range
print(array2[1:3 , 1:3])

[[50 60]
 [80 90]]


In [22]:
print(array2[0:2 , 0:2 ])

[[10 20]
 [40 50]]


In [23]:
print(array2[1:3 , ])

[[40 50 60]
 [70 80 90]]


In [24]:
print(array2[:, 1:3])

[[ 20  30]
 [ 50  60]
 [ 80  90]
 [110 120]]


In [25]:
print(array2[1:3, 1])

[50 80]


In [ ]:
# row and column after :1 means end value
print(array2[1:3, :1])

[[40]
 [70]]


In [ ]:
# row and column after 1: means start value
print(array2[1:3, 1:])

[[50 60]
 [80 90]]
