In [ ]:
'''
Broadcasting in NumPy

Broadcasting means NumPy automatically makes arrays compatible for mathematical operations 
even if their shapes are different.

It helps perform operations without writing loops.
'''

In [1]:
import numpy as np

In [ ]:
# Broadcasting with Scalar
'''
Explanation

5 is added to every element automatically.
'''

arr = np.array([10, 20, 30, 40])

result = arr + 5

print(result)

[15 25 35 45]


In [ ]:
# Broadcasting with Two Arrays
# Element-wise addition happens.
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2

print(result)

[11 22 33]


In [4]:
# Broadcasting Different Shapes

arr1 = np.array([[1], [2], [3]])

arr2 = np.array([10, 20, 30])

result = arr1 + arr2

print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
'''
How It Works

Shape of arrays:

arr1 shape = (3,1)
arr2 shape = (3,)


NumPy expands arrays automatically:

[[1],      [10 20 30]
 [2],  +   
 [3]]


Becomes:

[[11 21 31]
 [12 22 32]
 [13 23 33]]
'''


In [ ]:
'''
5. Broadcasting Rules

Two arrays are compatible when:

Dimensions are equal
OR
One dimension is 1
'''

In [ ]:
# Example with 15–20 Data
# Total elements = 5 × 4 = 20 values
arr1 = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])

arr2 = np.array([
    10,20,30,40
])

result = arr1 + arr2

print(result)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]
 [15 25 35 45]]


In [10]:
# 7. Broadcasting Error Example

arr1 = np.array([1,2,3])

arr2 = np.array([10,20])

print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# 9. Check Shape

print(arr1.shape)
print(arr2.shape)

(3,)
(2,)


In [ ]:
'''
Summary

| Concept             | Meaning                           |
| ------------------- | --------------------------------- |
| Broadcasting        | Automatic shape matching          |
| Scalar Broadcasting | One value applied to all elements |
| Compatible Shapes   | Same size or one dimension = 1    |
| Benefit             | Faster and less code              |

'''