In [ ]:
# Sorting 2d array

In [1]:
import numpy as np

In [ ]:
# default row wise sorting order follow

x = np.array([[12, 11, 15],
                [21, 25, 20],
                [18, 27, 16]])
y = np.sort(x)
#print(x)
print(y)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [ ]:
# coloumn wise sorting order follow
# column axis=0 and row axis=1

x = np.array([[12, 11, 15],
                [21, 25, 20],
                [18, 27, 16]])
y = np.sort(x, axis=0)
#print(x)
print(y)

[[12 11 15]
 [18 25 16]
 [21 27 20]]


In [ ]:
# argument concept it will return indexing value only
# rows wise sort 
#        0    1   2
# eg:-  [12, 11, 15] ans:[1, 0, 2]
#              0    1   2
x = np.array([[12, 11, 15],
                [21, 25, 20],
                [18, 27, 16]])
y = np.argsort(x, axis=1)
#print(x)
print(y)

[[1 0 2]
 [2 0 1]
 [2 0 1]]


In [ ]:
# column wise sort argument

x = np.array([[12, 11, 15],
                [21, 25, 20],
                [18, 27, 16]])
y = np.argsort(x, axis=0)
#print(x)
print(y)

[[0 0 0]
 [2 1 2]
 [1 2 1]]


In [ ]:
# in-place

x = np.array([[12, 11, 15],
                [21, 25, 20],
                [18, 27, 16]])
x.sort()
print(x)

[[11 12 15]
 [20 21 25]
 [16 18 27]]
