In [1]:
# NumPy stands or Numerical Python.
import numpy as np

In [2]:
# integer only
list1 =[10,20,30,40,50]
array1 = np.array(list1)
print(array1)

[10 20 30 40 50]


In [3]:
# nd means n-dimensional array. It is a generalization of 1D and 2D arrays to N dimensions.
type(array1)

numpy.ndarray

In [4]:
# integer and float mixed
list1 =[10,20.4,30,40,50]
array1 = np.array(list1)
print(array1)

[10.  20.4 30.  40.  50. ]


In [5]:
# intger and character mixed
list1 =[10,'hi',30,40,50]
array1 = np.array(list1)
print(array1)

['10' 'hi' '30' '40' '50']


In [6]:
list1 =[10,20,30,40,50]
array1 = np.array(list1, dtype='float') # dtype can be float, int, str, bool, U32(character)
print(array1)

[10. 20. 30. 40. 50.]


In [7]:
list1 = [[10,20,30],[40,50,60],[70,80,90]]
array1 = np.array(list1)
print(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
array1 = np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [9]:
array1 = np.arange(11,17).reshape(2,3)
print(array1)

[[11 12 13]
 [14 15 16]]


In [10]:
array1 = np.arange(11,17).reshape(3,2)
print(array1)

[[11 12]
 [13 14]
 [15 16]]


In [11]:
array1 = np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [12]:
array1 = np.zeros((4,2))
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
array1 = np.ones((4,2))
print(array1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# Array Fundamental
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
print(a[0])

1


In [16]:
# the original list, the array is mutable.
a[0] = 100
print(a)

[100   2   3   4   5   6   7   8   9  10]


In [17]:
# the original list, Python slice notation can be used for indexing.
print(a[:3])

[100   2   3]


In [18]:
'''
One major difference is that slice indexing of a list copies the elements into a new list, 
but slicing an array returns a view: an object that refers to the data in the original array. 
The original array can be mutated using the view.
'''
b = a[3:]
print(b)


[ 4  5  6  7  8  9 10]


In [19]:
b [0] =500
print(a)

[100   2   3 500   5   6   7   8   9  10]


In [20]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
# rows and coloums index no. print
print(a[0, 2])

3


In [ ]:
'''
Array attributes of NumPy
1. ndim, 
2. shape, 
3. size,
4. dtype 
5. itemsize
'''

In [ ]:
# ndim stands for number of dimensions (axes) of an array in NumPy.
# 1d array
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
array1.ndim

1

In [ ]:
# 2d array
list1 = [[100, 200, 300] , [400, 500, 600]]
array1 = np.array(list1)
array1.ndim

2

In [39]:
# 3d array
list1 = ([
            [[100, 200, 300] , [400, 500, 600]], 
            [[700, 800, 900] , [10, 20, 30]]
        
        ])
array1 = np.array(list1)
array1.ndim

3

In [ ]:
len(a.shape) == a.ndim

True

In [ ]:
# shape
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
#print(array1)
array1.shape

(5,)

In [42]:
# shape
list1 = [[100, 200, 300] , [400, 500, 600]]
array1 = np.array(list1)
print(array1)
array1.shape

[[100 200 300]
 [400 500 600]]


(2, 3)

In [43]:
# shape
list1 = [[100, 200, 300] , [400, 500, 600], [700, 800, 900]]
array1 = np.array(list1)
print(array1)
array1.shape

[[100 200 300]
 [400 500 600]
 [700 800 900]]


(3, 3)

In [45]:
# shape
list1 = ([
            [[100, 200, 300] , [400, 500, 600]], 
            [[700, 800, 900] , [10, 20, 30]]
        
        ])
array1 = np.array(list1)
print(array1)
array1.shape

[[[100 200 300]
  [400 500 600]]

 [[700 800 900]
  [ 10  20  30]]]


(2, 2, 3)

In [ ]:
# size
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
#print(array1)
array1.size

5

In [48]:
# size
list1 = [[100, 200, 300] , [400, 500, 600], [700, 800, 900]]
array1 = np.array(list1)
#print(array1)
array1.size

9

In [49]:
# size
list1 = ([
            [[100, 200, 300] , [400, 500, 600]], 
            [[700, 800, 900] , [10, 20, 30]]
        
        ])
array1 = np.array(list1)
#print(array1)
array1.size

12

In [50]:
# dtype
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
#print(array1)
array1.dtype

dtype('int64')

In [ ]:
# itemsize
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
#print(array1)
array1.itemsize

8

In [54]:
# itemsize foat
list1 = [10.45, 20.43, 30.22, 40.78, 50.54]
array1 = np.array(list1)
#print(array1)
array1.itemsize
#array1.dtype

8