In [ ]:
'''
Stacking in NumPy

Stacking means:

👉 Combining multiple arrays into one array.

NumPy provides:

hstack() → horizontal stack
vstack() → vertical stack
dstack() → depth stack
'''

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
'''
Horizontal Stacking (hstack)
Meaning
Join arrays side by side.
'''

np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [4]:
'''
Vertical Stacking (vstack)
Meaning
Join arrays row-wise.
'''

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
'''
Depth Stacking (dstack)
Used mostly in 3D arrays/images.
'''

np.dstack((a, b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [8]:
# Using concatenate()

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
'''
2. Splitting in NumPy
Splitting means:

👉 Breaking one array into multiple parts.

Functions:

split()
hsplit()
vsplit()
'''


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
# Meaning
# Split array into 3 equal parts.

np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [11]:
# Horizontal Split

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

np.hsplit(arr2, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [12]:
# Vertical Split

np.vsplit(arr2, 2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
'''
| Function   | Work                |
| ---------- | ------------------- |
| `hstack()` | join horizontally   |
| `vstack()` | join vertically     |
| `split()`  | divide array        |
| `hsplit()` | horizontal division |
| `vsplit()` | vertical division   |

'''