In [ ]:
'''
Save and Load Arrays in NumPy

NumPy provides functions to save arrays into files and load them later.

This is useful when:

Storing data permanently
Reusing arrays later
Saving machine learning datasets
'''

In [1]:
import numpy as np

In [2]:
# 1. Save Array using np.save()

a = np.array([10,20,30,40,50])

np.save("myarray.npy", a)

In [3]:
# 2. Load Array using np.load()

data = np.load("myarray.npy")

print(data)

[10 20 30 40 50]


In [4]:
'''
3. Save Multiple Arrays using np.savez()

Used to save multiple arrays in one file.
'''

a = np.array([1,2,3])

b = np.array([4,5,6])

np.savez("arrays.npz", first=a, second=b)

In [6]:
# 4. Load Multiple Arrays

data = np.load("arrays.npz")

print(data["first"])
print(data["second"])

[1 2 3]
[4 5 6]


In [7]:
'''
5. Save Text File using np.savetxt()

Stores array in text format.
'''

a = np.array([10,20,30,40])

np.savetxt("data.txt", a)

In [8]:
# 6. Load Text File using np.loadtxt()

data = np.loadtxt("data.txt")

print(data)

[10. 20. 30. 40.]


In [9]:
# 7. Save 2D Array

a = np.array([[1,2,3],
              [4,5,6]])

np.save("matrix.npy", a)

In [ ]:
# Load:

data = np.load("matrix.npy")

print(data)

[[1 2 3]
 [4 5 6]]


In [ ]:
'''
Important Functions

| Function       | Purpose              |
| -------------- | -------------------- |
| `np.save()`    | Save single array    |
| `np.load()`    | Load array           |
| `np.savez()`   | Save multiple arrays |
| `np.savetxt()` | Save text file       |
| `np.loadtxt()` | Load text file       |


Difference Between .npy and .txt

| `.npy`                  | `.txt`         |
| ----------------------- | -------------- |
| Faster                  | Slower         |
| Binary format           | Text format    |
| Better for NumPy arrays | Human readable |

'''

In [11]:
import numpy as np

a = np.array([100,200,300])

# save
np.save("numbers.npy", a)

# load
data = np.load("numbers.npy")

print(data)

[100 200 300]
