In [ ]:
'''
Linear Algebra Basics in NumPy

NumPy provides a special module called:

np.linalg

It is used for matrix operations like:-
Matrix addition
Matrix multiplication
Determinant
Inverse
Transpose
Eigen values
Dot product
'''

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
# 2. Matrix Addition

result = A + B

print(result)

[[ 6  8]
 [10 12]]


In [4]:
# 3. Matrix Subtraction

result = A - B
print(result)

[[-4 -4]
 [-4 -4]]


In [5]:
'''
4. Matrix Multiplication

Using dot():
'''

result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
# Or using @

result = A @ B

print(result)

[[19 22]
 [43 50]]


In [7]:
# 5. Transpose of Matrix

result = A.T

print(result)

[[1 3]
 [2 4]]


In [ ]:
# 6. Determinant of Matrix
# Determinant tells important properties of matrix

det_A = np.linalg.det(A)    
print(det_A)

-2.0000000000000004


In [ ]:
# 7. Inverse of Matrix
# Inverse exists only if determinant ≠ 0.

inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# 8. Eigen Values and Eigen Vectors

values, vectors = np.linalg.eig(A)

print("Eigen Values:")
print(values)

print("Eigen Vectors:")
print(vectors)

Eigen Values:
[-0.37228132  5.37228132]
Eigen Vectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# 9. Dot Product
'''
Calculation:

1×4+2×5+3×6=32
'''
a = np.array([1,2,3])

b = np.array([4,5,6])

result = np.dot(a,b)

print(result)

32


In [12]:
# 10. Identity Matrix

I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
'''
Important Functions

| Function          | Meaning               |
| ----------------- | --------------------- |
| `np.dot()`        | Matrix multiplication |
| `A.T`             | Transpose             |
| `np.linalg.det()` | Determinant           |
| `np.linalg.inv()` | Inverse               |
| `np.linalg.eig()` | Eigen values/vectors  |
| `np.eye()`        | Identity matrix       |

'''

In [13]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Addition")
print(A + B)

print("Multiplication")
print(np.dot(A,B))

print("Transpose")
print(A.T)

print("Determinant")
print(np.linalg.det(A))

Addition
[[ 6  8]
 [10 12]]
Multiplication
[[19 22]
 [43 50]]
Transpose
[[1 3]
 [2 4]]
Determinant
-2.0000000000000004
