In [ ]:
''' 
Arithmetic operation NumPy array
1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Matrix Multiplication (@)
5. Division (/)
6. Floor Division (//)
7. Exponentiation (**)
8. Module (%)
9. Transpose
'''

In [1]:
import numpy as np

In [ ]:
# 2d array
# 1. Addition (+) 

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = x + y
print(z)

[[12 14]
 [16 18]]


In [4]:
# 2. Subtraction (-)

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = y - x
print(z)

[[10 10]
 [10 10]]


In [5]:
# 3. Multiplication (*) 

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = x * y
print(z)

[[11 24]
 [39 56]]


In [6]:
# 4. Matrix Multiplication (@)

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = x @ y
print(z)

[[37 40]
 [85 92]]


In [ ]:
# 5. Division (/)
# it will return float value 

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = y / x
print(z)

[[11.          6.        ]
 [ 4.33333333  3.5       ]]


In [9]:
# 6. Floor Division (//)

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = y // x
print(z)

[[11  6]
 [ 4  3]]


In [ ]:
# 7. Exponentiation (**)
# Exponentiation means power (eg: 12**2=144)

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = y ** x
print(z)

[[   11   144]
 [ 2197 38416]]


In [ ]:
# 8. Module (%)
# reminder

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

z = y % x
print(z)

[[0 0]
 [1 2]]


In [ ]:
# 9. Transpose
# row will convert column
# column will convert row

x = np.array([[1 , 2],
              [3 , 4],])

y = np.array([[11 , 12],
              [13 , 14]])

print(x.transpose())

[[1 3]
 [2 4]]
