In [ ]:
'''
The random module in NumPy is used to generate random numbers, 
random arrays, shuffle data, and perform random sampling.
'''

In [1]:
import numpy as np

In [2]:
'''
Common Functions in NumPy Random Module
1. rand()

Generates random numbers between 0 and 1.

Example: 1D Array
'''

a = np.random.rand(5)
print(a)

[0.38450146 0.522767   0.71194907 0.15907672 0.35502484]


In [3]:
# Example: 2D Array

a = np.random.rand(2,3)
print(a)

[[0.1440542  0.4226061  0.41811094]
 [0.73108517 0.2519498  0.72017205]]


In [5]:
# 2. randint()

# Syntax: -np.random.randint(start, end, size)

a = np.random.randint(1, 10, 5)
print(a)

[1 5 6 9 4]


In [6]:
'''
3. randn()

Generates random numbers from normal distribution.
'''

a = np.random.randn(5)
print(a)

[-0.56241072 -0.44846815 -0.02672377  1.7966551   1.5937102 ]


In [7]:
# 4. choice()

a = np.random.choice([10,20,30,40], 3)
print(a)

[10 20 10]


In [8]:
# 5. seed()

np.random.seed(1)

print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [9]:
'''
6. shuffle()

Shuffles original array.
'''

a = np.array([1,2,3,4,5])

np.random.shuffle(a)

print(a)

[5 3 1 2 4]


In [10]:
'''
7. permutation()

Returns shuffled array without changing original array.
'''

a = np.array([1,2,3,4,5])

b = np.random.permutation(a)

print(b)
print(a)

[3 4 5 1 2]
[1 2 3 4 5]


In [ ]:
'''
Difference Between shuffle() and permutation()

| Function      | Original Array Changes? |
| ------------- | ----------------------- |
| shuffle()     | Yes                     |
| permutation() | No                      |


Important Notes
rand() → decimal numbers
randint() → integer numbers
randn() → normal distribution values
choice() → random selection
shuffle() → changes original array
seed() → fixed random output
'''

In [11]:
import numpy as np

# random integers
a = np.random.randint(1, 100, 10)

print(a)

# shuffle
np.random.shuffle(a)

print("After shuffle:", a)

[ 7 26 51 21 19 85 12 29 30 15]
After shuffle: [30 21 85 15  7 12 26 29 19 51]
