In [ ]:
'''
Sorting 1d array
1. np.sort() --> it will return a sorted copy of an array
2. np.argsort() --> it will return indices that would sort an array
3. ndarray.sort() --> use array name and sort it in-place
'''

In [1]:
import numpy as np

In [ ]:
# ascending order of rows default
x = np.array([7, 2, 3, 9, 6])
y = np.sort(x)
print(y)

[2 3 6 7 9]


In [ ]:
# use silicing for reverse / descending order
x = np.array([7, 2, 3, 9, 6])
y = np.sort(x)[::-1]
print(y)

[9 7 6 3 2]


In [3]:
x = np.array([7, 2, 3, 9, 6])
y = np.argsort(x)
print(y)

[1 2 4 0 3]


In [5]:
x = np.array([7, 2, 3, 9, 6])
x.sort()
print(x)

[2 3 6 7 9]
